version: '3.8'

services:
  wallet_db:
    image: postgres:15-alpine
    container_name: postgres_wallet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rahasia 
      - POSTGRES_DB=wallet_db
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data 
  app-wallet:
    image: hanifsholihin/wallet-api:latest
    container_name: wallet_api_container
    ports:
      - "5000:5000" 
    environment:
      - DB_HOST=wallet_db
      - DB_USER=postgres
      - DB_PASSWORD=rahasia
      - DB_NAME=wallet_db
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - SECRET_KEY=kuncirahasia-sangat-rahasia-32ch
    depends_on:
      - wallet_db

volumes:
  db_data: