version: '3.8'

services:
  wallet_db:
    image: postgres:15-alpine
    container_name: postgres_wallet
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posgtres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/postgresql/data 
  app-wallet:
    image: hanifsholihin/wallet-api:latest
    container_name: wallet_api_container
    ports:
      - "5000:5000" 
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_HOST}
      - DB_SSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      wallet_db :
        condition: service_healthy
    restart: always

volumes:
  db_data: